# -*- mode: yaml-*-
# vi: set ft=yaml sw=2 ts=2 :

- name: Configure redis
  hosts: all
  sudo: True
  tasks:
    - name: set locale
      lineinfile: dest=/etc/default/locale line="LC_ALL=C"

    - name: install packages
      apt: name={{ item }} update_cache=yes
      with_items:
        - git
        - curl

    - name: install pip
      shell: curl https://bootstrap.pypa.io/get-pip.py | python -


    - name: add ppa with node and redis
      shell: curl -sL https://deb.nodesource.com/setup | bash -

    - name: install node and npm
      apt: name=nodejs update_cache=yes

    - name: install docker
      shell: curl -sSL https://get.docker.com/ | sh
      args:
        creates: /usr/bin/docker

    - name: install redis
      apt: name=redis-server update_cache=yes

    - name: Create user redis
      user: name=redis system=yes home=/var/lib/redis shell=/bin/false


    - name: Install docker-py
      pip: name=docker-py version=1.1.0


    - name: install node dependencies
      npm: path=/opt/project

    - name: install compose
      pip: name=docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: change working directory
      lineinfile: dest=/home/vagrant/.bashrc line='cd /opt/project'

    - name: Start Redis
      service: name=redis-server state=started


  handlers:
    - name: Restart Redis
      service: name=redis state=restarted
